# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import restaurant_pb2 as restaurant__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in restaurant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestaurantServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchById = channel.unary_unary(
                '/restaurant.RestaurantService/SearchById',
                request_serializer=restaurant_dot_restaurant__pb2.IdRequest.SerializeToString,
                response_deserializer=restaurant_dot_restaurant__pb2.RestaurantList.FromString,
                _registered_method=True)
        self.SearchByName = channel.unary_unary(
                '/restaurant.RestaurantService/SearchByName',
                request_serializer=restaurant__pb2.SearchRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantList.FromString,
                _registered_method=True)
        self.SearchByType = channel.unary_unary(
                '/restaurant.RestaurantService/SearchByType',
                request_serializer=restaurant__pb2.TypeRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantList.FromString,
                _registered_method=True)
        self.SearchByCategorie = channel.unary_unary(
                '/restaurant.RestaurantService/SearchByCategorie',
                request_serializer=restaurant__pb2.CategorieRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantList.FromString,
                _registered_method=True)
        self.SearchByLocation = channel.unary_unary(
                '/restaurant.RestaurantService/SearchByLocation',
                request_serializer=restaurant__pb2.LocationRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantList.FromString,
                _registered_method=True)
        self.SearchByContact = channel.unary_unary(
                '/restaurant.RestaurantService/SearchByContact',
                request_serializer=restaurant__pb2.ContactRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantList.FromString,
                _registered_method=True)
        self.SearchByCapacity = channel.unary_unary(
                '/restaurant.RestaurantService/SearchByCapacity',
                request_serializer=restaurant__pb2.CapacityRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantList.FromString,
                _registered_method=True)
        self.SearchByStatus = channel.unary_unary(
                '/restaurant.RestaurantService/SearchByStatus',
                request_serializer=restaurant__pb2.StatusRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantList.FromString,
                _registered_method=True)


class RestaurantServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByCategorie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchById': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchById,
                    request_deserializer=restaurant_dot_restaurant__pb2.IdRequest.FromString,
                    response_serializer=restaurant_dot_restaurant__pb2.RestaurantList.SerializeToString,
            ),
            'SearchByName': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByName,
                    request_deserializer=restaurant__pb2.SearchRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantList.SerializeToString,
            ),
            'SearchByType': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByType,
                    request_deserializer=restaurant__pb2.TypeRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantList.SerializeToString,
            ),
            'SearchByCategorie': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByCategorie,
                    request_deserializer=restaurant__pb2.CategorieRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantList.SerializeToString,
            ),
            'SearchByLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByLocation,
                    request_deserializer=restaurant__pb2.LocationRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantList.SerializeToString,
            ),
            'SearchByContact': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByContact,
                    request_deserializer=restaurant__pb2.ContactRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantList.SerializeToString,
            ),
            'SearchByCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByCapacity,
                    request_deserializer=restaurant__pb2.CapacityRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantList.SerializeToString,
            ),
            'SearchByStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByStatus,
                    request_deserializer=restaurant__pb2.StatusRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('restaurant.RestaurantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SearchById',
            restaurant_dot_restaurant__pb2.IdRequest.SerializeToString,
            restaurant_dot_restaurant__pb2.RestaurantList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SearchByName',
            restaurant__pb2.SearchRequest.SerializeToString,
            restaurant__pb2.RestaurantList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SearchByType',
            restaurant__pb2.TypeRequest.SerializeToString,
            restaurant__pb2.RestaurantList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByCategorie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SearchByCategorie',
            restaurant__pb2.CategorieRequest.SerializeToString,
            restaurant__pb2.RestaurantList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SearchByLocation',
            restaurant__pb2.LocationRequest.SerializeToString,
            restaurant__pb2.RestaurantList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SearchByContact',
            restaurant__pb2.ContactRequest.SerializeToString,
            restaurant__pb2.RestaurantList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SearchByCapacity',
            restaurant__pb2.CapacityRequest.SerializeToString,
            restaurant__pb2.RestaurantList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SearchByStatus',
            restaurant__pb2.StatusRequest.SerializeToString,
            restaurant__pb2.RestaurantList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
