# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: restaurant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'restaurant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10restaurant.proto\x12\nrestaurant\"\x07\n\x05\x45mpty\"\x1b\n\x0b\x43ityRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"\x1b\n\x0bNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"=\n\x0eRestaurantList\x12+\n\x0brestaurants\x18\x01 \x03(\x0b\x32\x16.restaurant.Restaurant\"G\n\nRestaurant\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t2\xef\x01\n\x11RestaurantService\x12\x42\n\x11GetAllRestaurants\x12\x11.restaurant.Empty\x1a\x1a.restaurant.RestaurantList\x12J\n\x13GetRestaurantByCity\x12\x17.restaurant.CityRequest\x1a\x1a.restaurant.RestaurantList\x12J\n\x13GetRestaurantByName\x12\x17.restaurant.NameRequest\x1a\x1a.restaurant.RestaurantListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_CITYREQUEST']._serialized_start=41
  _globals['_CITYREQUEST']._serialized_end=68
  _globals['_NAMEREQUEST']._serialized_start=70
  _globals['_NAMEREQUEST']._serialized_end=97
  _globals['_RESTAURANTLIST']._serialized_start=99
  _globals['_RESTAURANTLIST']._serialized_end=160
  _globals['_RESTAURANT']._serialized_start=162
  _globals['_RESTAURANT']._serialized_end=233
  _globals['_RESTAURANTSERVICE']._serialized_start=236
  _globals['_RESTAURANTSERVICE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
